export default function Disclaimer() {
  return (
    <div className="max-w-3xl mx-auto py-8 px-4">
      <h1 className="mb-2" style={{ color: '#0f172a' }}>Site Disclaimer</h1>
      <p className="mb-8 text-sm" style={{ color: '#64748b' }}>Last updated: April 2026</p>

      {/* General */}
      <section className="mb-8 p-5 rounded-2xl" style={{ background: '#fff', border: '1px solid #e2e8f0' }}>
        <h2 className="mb-3" style={{ color: '#0f172a', fontSize: '1.1rem' }}>General Disclaimer</h2>
        <p className="text-sm leading-relaxed" style={{ color: '#475569' }}>
          TrueOddsIQ (trueoddsiq.com) is an independent sports odds comparison and information platform.
          We do not accept wagers, facilitate gambling, or operate as a sportsbook of any kind.
          All odds data displayed on this site is provided for informational and educational purposes only
          and may not reflect the most current lines available at any given sportsbook.
          Users are strongly encouraged to verify current odds directly with their sportsbook before placing any wager.
          You must be 21 years of age or older and located in a jurisdiction where sports betting is legally permitted
          to place wagers with any sportsbook.
        </p>
      </section>

      {/* AI Disclaimer */}
      <section className="mb-8 p-5 rounded-2xl" style={{ background: '#fff', border: '1px solid #e2e8f0' }}>
        <h2 className="mb-3" style={{ color: '#0f172a', fontSize: '1.1rem' }}>AI Analysis & AI Picks Disclaimer</h2>
        <p className="text-sm leading-relaxed mb-3" style={{ color: '#475569' }}>
          Predictions, analysis, and picks generated by artificial intelligence tools (including Claude and ChatGPT)
          on this platform are based solely on publicly available odds data and statistical modeling.
          They are provided for informational purposes only and are <strong>not guaranteed to be accurate, complete, or profitable.</strong>
        </p>
        <p className="text-sm leading-relaxed mb-3" style={{ color: '#475569' }}>
          AI-generated content should not be solely relied upon when making wagering decisions.
          Past performance of any AI pick or analysis does not guarantee future results.
          Users should exercise their own independent judgment before placing any wager.
        </p>
        <p className="text-sm leading-relaxed mb-3" style={{ color: '#475569' }}>
          All sports betting involves significant financial risk. You should only wager amounts you are fully prepared to lose.
        </p>
        <div className="p-3 rounded-xl" style={{ background: '#fef2f2', border: '1px solid #fecaca' }}>
          <p className="text-sm font-semibold" style={{ color: '#dc2626' }}>
            TrueOddsIQ and its operators shall not be held liable for any losses, financial or otherwise,
            resulting from wagering decisions made in whole or in part based on content, analysis, picks,
            or odds data displayed on this site. All wagering is done entirely at the user's own risk.
          </p>
        </div>
      </section>

      {/* Odds Data */}
      <section className="mb-8 p-5 rounded-2xl" style={{ background: '#fff', border: '1px solid #e2e8f0' }}>
        <h2 className="mb-3" style={{ color: '#0f172a', fontSize: '1.1rem' }}>Odds Data Disclaimer</h2>
        <p className="text-sm leading-relaxed" style={{ color: '#475569' }}>
          Odds shown on TrueOddsIQ are sourced from third-party data providers and are refreshed periodically.
          Lines may have moved since the last update. TrueOddsIQ makes no representations or warranties
          regarding the accuracy, timeliness, or completeness of any odds data displayed.
          Always verify current odds directly with your sportsbook before placing a bet.
        </p>
      </section>

      {/* Affiliate Links */}
      <section className="mb-8 p-5 rounded-2xl" style={{ background: '#fff', border: '1px solid #e2e8f0' }}>
        <h2 className="mb-3" style={{ color: '#0f172a', fontSize: '1.1rem' }}>Affiliate Disclosure</h2>
        <p className="text-sm leading-relaxed" style={{ color: '#475569' }}>
          TrueOddsIQ may earn a commission when users sign up with sportsbooks through links on this site.
          This does not affect the odds data we display or our editorial independence.
          Sportsbook links are provided for user convenience only.
        </p>
      </section>

      {/* Responsible Gambling */}
      <section className="p-5 rounded-2xl" style={{ background: '#f0fdf4', border: '1px solid #bbf7d0' }}>
        <h2 className="mb-3" style={{ color: '#15803d', fontSize: '1.1rem' }}>Responsible Gambling</h2>
        <p className="text-sm leading-relaxed mb-3" style={{ color: '#475569' }}>
          Gambling should be entertaining and done responsibly. If you or someone you know is struggling
          with a gambling problem, free and confidential help is available 24/7:
        </p>
        <div className="flex flex-col gap-2">
          <a href="tel:1-800-426-2537" className="text-sm font-bold" style={{ color: '#15803d' }}>
            📞 National Problem Gambling Helpline: 1-800-GAMBLER (1-800-426-2537)
          </a>
          <a href="https://www.ncpgambling.org" target="_blank" rel="noopener noreferrer"
            className="text-sm font-bold" style={{ color: '#15803d' }}>
            🌐 ncpgambling.org
          </a>
          <a href="https://www.gamblingtherapy.org" target="_blank" rel="noopener noreferrer"
            className="text-sm font-bold" style={{ color: '#15803d' }}>
            🌐 gamblingtherapy.org
          </a>
        </div>
      </section>
    </div>
  )
}
