export default function AIDisclaimer() {
  return (
    <div className="flex items-start gap-3 p-3 rounded-xl mb-5"
      style={{ background: '#fffbeb', border: '1px solid #fde68a' }}>
      <span style={{ fontSize: 18, lineHeight: 1 }}>⚠️</span>
      <p className="text-xs leading-relaxed" style={{ color: '#92400e' }}>
        <strong>AI Analysis Disclaimer:</strong> Picks and analysis are generated by AI based on publicly available odds data.
        They are not guaranteed to be accurate and should not be solely relied upon when wagering.
        TrueOddsIQ shall not be liable for any losses resulting from wagers placed based on content displayed on this site.
        All betting is done at your own risk. Bet responsibly.
      </p>
    </div>
  )
}
